//Products action types
export const REQUEST_PRODUCTS_SENT = "REQUEST_PRODUCTS_SENT";
export const REQUEST_PRODUCTS_SUCCESS = "REQUEST_SUCCESS_PRODUCTS";
export const REQUEST_PRODUCTS_FAIL = "REQUEST_PRODUCTS_FAIL";

export const REQUEST_PRODUCTS_DETAIL_SENT = "REQUEST_PRODUCTS_DETAIL_SENT";
export const REQUEST_PRODUCTS_DETAIL_SUCCESS =
  "REQUEST_PRODUCTS_DETAIL_SUCCESS ";
export const REQUEST_PRODUCTS_DETAIL_FAIL = "REQUEST_PRODUCTS_DETAIL_FAIL";

// Cart action types
export const ADD_TO_SHOPPINGCART = "ADD_TO_SHOPPINGCART";
export const REMOVE_FROM_SHOPPINGCART = "REMOVE_FROM_SHOPPINGCART";
